export const dsaTopics = [
  {
    title: "Arrays",
    slug: "arrays",
    difficulty: "Beginner",
    description:
      "Start with indexing, traversal, prefix sums, two pointers, and sliding window basics.",
    roadmapOrder: 1,
    patterns: [
      "Traversal and indexing",
      "Two pointers",
      "Sliding window",
      "Prefix sum",
    ],
    status: "In Progress",
    problems: [
      {
        title: "Two Sum",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/two-sum/",
        status: "Completed",
      },
      {
        title: "Best Time to Buy and Sell Stock",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        status: "Planned",
      },
      {
        title: "Contains Duplicate",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/contains-duplicate/",
        status: "Completed",
      },
      {
        title: "Product of Array Except Self",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/product-of-array-except-self/",
        status: "In Progress",
      },
    ],
  },
  {
    title: "Strings",
    slug: "strings",
    difficulty: "Beginner",
    description:
      "Build confidence with frequency maps, pattern matching, palindromes, and substring logic.",
    roadmapOrder: 2,
    patterns: [
      "Frequency counting",
      "Palindrome checks",
      "Substring scanning",
      "Hash map lookups",
    ],
    status: "Planned",
    problems: [
      {
        title: "Valid Anagram",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/valid-anagram/",
        status: "Planned",
      },
      {
        title: "Longest Common Prefix",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/longest-common-prefix/",
        status: "Planned",
      },
      {
        title: "Longest Substring Without Repeating Characters",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        status: "In Progress",
      },
      {
        title: "Group Anagrams",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/group-anagrams/",
        status: "Planned",
      },
    ],
  },
  {
    title: "Linked List",
    slug: "linked-list",
    difficulty: "Intermediate",
    description:
      "Practice node traversal, reversal, fast-slow pointers, and cycle detection patterns.",
    roadmapOrder: 3,
    patterns: [
      "Pointer updates",
      "Fast and slow pointers",
      "Reversal",
      "Dummy nodes",
    ],
    status: "Planned",
    problems: [
      {
        title: "Reverse Linked List",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/reverse-linked-list/",
        status: "Planned",
      },
      {
        title: "Linked List Cycle",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/linked-list-cycle/",
        status: "Planned",
      },
      {
        title: "Merge Two Sorted Lists",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/merge-two-sorted-lists/",
        status: "In Progress",
      },
      {
        title: "Remove Nth Node From End of List",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
        status: "Planned",
      },
    ],
  },
  {
    title: "Stack",
    slug: "stack",
    difficulty: "Intermediate",
    description:
      "Learn LIFO problem solving with balanced brackets, monotonic stacks, and undo-style flows.",
    roadmapOrder: 4,
    patterns: [
      "LIFO operations",
      "Monotonic stack",
      "Expression parsing",
      "State rollback",
    ],
    status: "Planned",
    problems: [
      {
        title: "Valid Parentheses",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/valid-parentheses/",
        status: "Completed",
      },
      {
        title: "Min Stack",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/min-stack/",
        status: "Planned",
      },
      {
        title: "Daily Temperatures",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/daily-temperatures/",
        status: "Planned",
      },
      {
        title: "Evaluate Reverse Polish Notation",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
        status: "In Progress",
      },
    ],
  },
  {
    title: "Queue",
    slug: "queue",
    difficulty: "Intermediate",
    description:
      "Cover FIFO thinking with BFS foundations, deque patterns, and scheduling-style problems.",
    roadmapOrder: 5,
    patterns: [
      "FIFO processing",
      "Deque usage",
      "Breadth-first search",
      "Window maintenance",
    ],
    status: "Planned",
    problems: [
      {
        title: "Implement Queue using Stacks",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/implement-queue-using-stacks/",
        status: "Planned",
      },
      {
        title: "Number of Recent Calls",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/number-of-recent-calls/",
        status: "Planned",
      },
      {
        title: "Sliding Window Maximum",
        difficulty: "Hard",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/sliding-window-maximum/",
        status: "Planned",
      },
      {
        title: "Dota2 Senate",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/dota2-senate/",
        status: "In Progress",
      },
    ],
  },
  {
    title: "Trees",
    slug: "trees",
    difficulty: "Intermediate",
    description:
      "Work through DFS, BFS, recursion, binary tree properties, and traversal patterns.",
    roadmapOrder: 6,
    patterns: [
      "DFS recursion",
      "BFS level order",
      "Binary search tree rules",
      "Tree height and depth",
    ],
    status: "Planned",
    problems: [
      {
        title: "Maximum Depth of Binary Tree",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
        status: "Planned",
      },
      {
        title: "Invert Binary Tree",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/invert-binary-tree/",
        status: "Completed",
      },
      {
        title: "Binary Tree Level Order Traversal",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        status: "Planned",
      },
      {
        title: "Validate Binary Search Tree",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/validate-binary-search-tree/",
        status: "In Progress",
      },
    ],
  },
  {
    title: "Graphs",
    slug: "graphs",
    difficulty: "Advanced",
    description:
      "Explore adjacency lists, traversal, connected components, and shortest path ideas.",
    roadmapOrder: 7,
    patterns: [
      "Graph traversal",
      "Visited sets",
      "Connected components",
      "Shortest path reasoning",
    ],
    status: "Planned",
    problems: [
      {
        title: "Number of Islands",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/number-of-islands/",
        status: "Planned",
      },
      {
        title: "Clone Graph",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/clone-graph/",
        status: "Planned",
      },
      {
        title: "Course Schedule",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/course-schedule/",
        status: "In Progress",
      },
      {
        title: "Pacific Atlantic Water Flow",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
        status: "Planned",
      },
    ],
  },
  {
    title: "Dynamic Programming",
    slug: "dynamic-programming",
    difficulty: "Advanced",
    description:
      "Finish with memoization, tabulation, state transitions, and optimization strategies.",
    roadmapOrder: 8,
    patterns: [
      "Memoization",
      "Tabulation",
      "State transition design",
      "Optimization over subproblems",
    ],
    status: "Completed",
    problems: [
      {
        title: "Climbing Stairs",
        difficulty: "Easy",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/climbing-stairs/",
        status: "Completed",
      },
      {
        title: "House Robber",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/house-robber/",
        status: "Completed",
      },
      {
        title: "Coin Change",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/coin-change/",
        status: "In Progress",
      },
      {
        title: "Longest Increasing Subsequence",
        difficulty: "Medium",
        platform: "LeetCode",
        url: "https://leetcode.com/problems/longest-increasing-subsequence/",
        status: "Planned",
      },
    ],
  },
];

export const dsaTopicSlugs = dsaTopics.map((topic) => topic.slug);

export function getDsaTopicBySlug(slug) {
  return dsaTopics.find((topic) => topic.slug === slug);
}
